version: '3.8'

services:

  db:
    container_name: cities-api-db
    image: postgres
    restart: always
    networks:
      - cities-api-network
    volumes:
      - cities-api-data:/var/lib/postgresql/data
      - ./schemas:/docker-entrypoint-initdb.d
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cities

  adminer:
    container_name: cities-api-adminer
    image: adminer
    restart: always
    networks:
      - cities-api-network
    ports:
      - 8080:8080

networks:
  cities-api-network:
    name: cities-api

volumes:
  cities-api-data:
    name: cities-api
