server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cities
    username: postgres
    password: postgres

  jpa:
    show-sql: true
    properties:
      hibernate:
        format-sql: true
